/**
 * GiftService
 * 
 * Core service for creating, managing, and sharing game gifts.
 */

import AsyncStorage from '@react-native-async-storage/async-storage';
import {
  Gift,
  GiftStatus,
  GiftCreationMode,
  GiftRecipient,
  GiftWrap,
  GiftNote,
  GiftReaction,
  CreateGiftInput,
  UpdateGiftInput,
  RouletteResult,
  BlindDateConfig,
  DEFAULT_GIFT_WRAP,
} from '../types/gift';
import { generateId } from '../utils/helpers';
import { rouletteService } from './RouletteService';

const STORAGE_KEY = '@giftforge/gifts';
const SHORT_CODE_CHARS = 'abcdefghjkmnpqrstuvwxyz23456789'; // No confusing chars

class GiftService {
  private gifts: Map<string, Gift> = new Map();
  private shortCodeMap: Map<string, string> = new Map(); // shortCode -> giftId
  private initialized: boolean = false;

  /**
   * Initialize the service
   */
  async initialize(): Promise<void> {
    if (this.initialized) return;

    try {
      const saved = await AsyncStorage.getItem(STORAGE_KEY);
      if (saved) {
        const giftsArray: Gift[] = JSON.parse(saved);
        giftsArray.forEach(gift => {
          this.gifts.set(gift.id, {
            ...gift,
            createdAt: new Date(gift.createdAt),
            sharedAt: gift.sharedAt ? new Date(gift.sharedAt) : undefined,
            openedAt: gift.openedAt ? new Date(gift.openedAt) : undefined,
            firstPlayedAt: gift.firstPlayedAt ? new Date(gift.firstPlayedAt) : undefined,
          });
          this.shortCodeMap.set(gift.shortCode, gift.id);
        });
      }
      this.initialized = true;
    } catch (error) {
      console.error('Failed to load gifts:', error);
      this.initialized = true;
    }
  }

  /**
   * Save gifts to storage
   */
  private async saveGifts(): Promise<void> {
    try {
      const giftsArray = Array.from(this.gifts.values());
      await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(giftsArray));
    } catch (error) {
      console.error('Failed to save gifts:', error);
    }
  }

  /**
   * Generate a short code for sharing
   */
  private generateShortCode(): string {
    let code: string;
    do {
      code = 'gf-';
      for (let i = 0; i < 5; i++) {
        code += SHORT_CODE_CHARS.charAt(Math.floor(Math.random() * SHORT_CODE_CHARS.length));
      }
    } while (this.shortCodeMap.has(code));
    return code;
  }

  /**
   * Create a new gift
   */
  async createGift(input: CreateGiftInput): Promise<Gift> {
    await this.initialize();

    const id = generateId();
    const shortCode = this.generateShortCode();
    const now = new Date();

    let templateId = input.templateId || '';
    let artStyleId = input.artStyleId || '';
    let rouletteResult: RouletteResult | undefined;

    // If roulette mode, spin for random combo
    if (input.mode === 'roulette') {
      rouletteResult = await rouletteService.spinRoulette(input.rouletteConfig);
      templateId = rouletteResult.templateId;
      artStyleId = rouletteResult.artStyleId;
    }

    const gift: Gift = {
      id,
      gameId: `game-${id}`,
      templateId,
      artStyleId,
      creatorId: undefined,
      creatorName: input.creatorName,
      recipient: input.recipient,
      mode: input.mode,
      rouletteResult,
      blindDateConfig: input.blindDateConfig ? {
        ...input.blindDateConfig,
        easterEggs: [], // Will be generated by AI
      } : undefined,
      wrap: input.wrap || DEFAULT_GIFT_WRAP,
      note: input.note ? { ...input.note, createdAt: now } : undefined,
      shareLink: `https://giftforge.app/g/${shortCode}`,
      shortCode,
      status: 'created',
      createdAt: now,
      reactions: [],
      playCount: 0,
    };

    this.gifts.set(id, gift);
    this.shortCodeMap.set(shortCode, id);
    await this.saveGifts();

    return gift;
  }

  /**
   * Get gift by ID
   */
  async getGiftById(id: string): Promise<Gift | null> {
    await this.initialize();
    return this.gifts.get(id) || null;
  }

  /**
   * Get gift by short code
   */
  async getGiftByShortCode(shortCode: string): Promise<Gift | null> {
    await this.initialize();
    const giftId = this.shortCodeMap.get(shortCode);
    if (!giftId) return null;
    return this.gifts.get(giftId) || null;
  }

  /**
   * Update a gift
   */
  async updateGift(id: string, updates: UpdateGiftInput): Promise<Gift | null> {
    await this.initialize();
    
    const gift = this.gifts.get(id);
    if (!gift) return null;

    const updatedGift: Gift = {
      ...gift,
      ...(updates.wrap && { wrap: updates.wrap }),
      ...(updates.note && { note: { ...updates.note, createdAt: new Date() } }),
      ...(updates.status && { status: updates.status }),
    };

    this.gifts.set(id, updatedGift);
    await this.saveGifts();

    return updatedGift;
  }

  /**
   * Mark gift as shared
   */
  async markAsShared(id: string): Promise<Gift | null> {
    await this.initialize();
    
    const gift = this.gifts.get(id);
    if (!gift) return null;

    const updatedGift: Gift = {
      ...gift,
      status: 'shared',
      sharedAt: new Date(),
    };

    this.gifts.set(id, updatedGift);
    await this.saveGifts();

    return updatedGift;
  }

  /**
   * Mark gift as opened (by recipient)
   */
  async markAsOpened(id: string): Promise<Gift | null> {
    await this.initialize();
    
    const gift = this.gifts.get(id);
    if (!gift) return null;

    const updatedGift: Gift = {
      ...gift,
      status: 'opened',
      openedAt: new Date(),
    };

    this.gifts.set(id, updatedGift);
    await this.saveGifts();

    return updatedGift;
  }

  /**
   * Mark gift as played
   */
  async markAsPlayed(id: string): Promise<Gift | null> {
    await this.initialize();
    
    const gift = this.gifts.get(id);
    if (!gift) return null;

    const updatedGift: Gift = {
      ...gift,
      status: 'played',
      firstPlayedAt: gift.firstPlayedAt || new Date(),
      playCount: gift.playCount + 1,
    };

    this.gifts.set(id, updatedGift);
    await this.saveGifts();

    return updatedGift;
  }

  /**
   * Add reaction to gift
   */
  async addReaction(id: string, reaction: Omit<GiftReaction, 'id' | 'createdAt'>): Promise<Gift | null> {
    await this.initialize();
    
    const gift = this.gifts.get(id);
    if (!gift) return null;

    const newReaction: GiftReaction = {
      id: generateId(),
      ...reaction,
      createdAt: new Date(),
    };

    const updatedGift: Gift = {
      ...gift,
      reactions: [...gift.reactions, newReaction],
    };

    this.gifts.set(id, updatedGift);
    await this.saveGifts();

    return updatedGift;
  }

  /**
   * Get all gifts created by user
   */
  async getMyGifts(): Promise<Gift[]> {
    await this.initialize();
    return Array.from(this.gifts.values())
      .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  }

  /**
   * Get gifts by status
   */
  async getGiftsByStatus(status: GiftStatus): Promise<Gift[]> {
    await this.initialize();
    return Array.from(this.gifts.values())
      .filter(g => g.status === status)
      .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  }

  /**
   * Get gift statistics
   */
  async getStatistics(): Promise<{
    totalGifts: number;
    byStatus: Record<GiftStatus, number>;
    byMode: Record<GiftCreationMode, number>;
    totalReactions: number;
    totalPlays: number;
  }> {
    await this.initialize();

    const gifts = Array.from(this.gifts.values());
    
    const byStatus: Record<GiftStatus, number> = {
      draft: 0,
      created: 0,
      shared: 0,
      opened: 0,
      played: 0,
    };

    const byMode: Record<GiftCreationMode, number> = {
      standard: 0,
      roulette: 0,
      blind_date: 0,
    };

    let totalReactions = 0;
    let totalPlays = 0;

    gifts.forEach(gift => {
      byStatus[gift.status]++;
      byMode[gift.mode]++;
      totalReactions += gift.reactions.length;
      totalPlays += gift.playCount;
    });

    return {
      totalGifts: gifts.length,
      byStatus,
      byMode,
      totalReactions,
      totalPlays,
    };
  }

  /**
   * Delete a gift
   */
  async deleteGift(id: string): Promise<boolean> {
    await this.initialize();
    
    const gift = this.gifts.get(id);
    if (!gift) return false;

    this.gifts.delete(id);
    this.shortCodeMap.delete(gift.shortCode);
    await this.saveGifts();

    return true;
  }

  /**
   * Clear all gifts (for testing)
   */
  async clearAll(): Promise<void> {
    this.gifts.clear();
    this.shortCodeMap.clear();
    await AsyncStorage.removeItem(STORAGE_KEY);
  }
}

export const giftService = new GiftService();
export { GiftService };
