/**
 * CrewAI Agent Types for Game Development
 * 
 * System Philosophy:
 * - Games are products, not art projects
 * - Monetization > virality
 * - Automation > engagement tricks
 * - Small paid audiences > massive free users
 */

// Agent Base Types
export interface CrewAIAgent {
  role: string;
  goal: string;
  backstory: string;
  strictInstructions: string[];
  autoRejectConditions: string[];
}

// Agent 1: Game Concept Sniper Types
export interface GameConceptOutput {
  gameConcept: string;
  targetAudience: string;
  coreGameLoop: string[]; // max 3 steps
  whatAIGenerates: string;
  whyUsersPay: string;
}

export interface GameConceptValidation {
  isSinglePlayer: boolean;
  isContentAutoGenerated: boolean;
  isWebFirst: boolean;
  coreLoopSteps: number;
  requiresManualDesign: boolean;
  isMultiplayer: boolean;
  needsWeeklyUpdates: boolean;
  dependsOnAdsOrVirality: boolean;
}

// Agent 2: Game Monetization Enforcer Types
export type MonetizationModel = 'subscription' | 'paid_unlocks' | 'b2b_licensing';

export interface MonetizationOutput {
  pricePointAED: number;
  paidUsersFor10kAED: number;
  paidUsersFor20kAED: number;
  expectedConversionRate: string;
  whyUsersPay: string;
  churnRisk: {
    level: 'Low' | 'Medium' | 'High';
    reason: string;
  };
}

export interface MonetizationValidation {
  model: MonetizationModel;
  usesAds: boolean;
  requiredMAU: number;
  arpu: number;
  hasMonetizationPlan: boolean;
}

// Agent 3: Game Automation Architect Types
export interface AutomationOutput {
  intake: string;
  aiProcessing: string;
  gameLogic: string;
  output: string;
  automationScore: number; // percentage
  humanInterventionRequired: {
    required: boolean;
    reason: string;
  };
}

export interface AutomationValidation {
  contentGenerationAutomated: boolean;
  difficultyScalingAutomated: boolean;
  refreshCadenceAutomated: boolean;
  manualModerationRequired: boolean;
  automationPercentage: number;
  requiresFrequentReleases: boolean;
}

// Agent 4: Kill-Switch Governor Types
export interface KillSwitchScore {
  monetizationStrength: {
    paidFirstModel: number; // max 15
    arpuThreshold: number; // max 10 (ARPU >= AED 20)
    userThreshold: number; // max 10 (≤1,000 users for AED 20k)
    total: number; // max 35
  };
  automationContent: {
    aiGeneratedContent: number; // max 15
    noManualUpdates: number; // max 10
    simpleLoop: number; // max 5
    total: number; // max 30
  };
  retentionLogic: {
    returnTrigger: number; // max 10 (daily/weekly return trigger)
    progressionWithoutContent: number; // max 5
    noMultiplayerDependency: number; // max 5
    total: number; // max 20
  };
  executionSimplicity: {
    webDeployable: number; // max 5
    noAppStoreDependency: number; // max 5
    lowMaintenance: number; // max 5 (≤2 hrs/week)
    total: number; // max 15
  };
  finalScore: number; // max 100
}

export interface KillSwitchOutput {
  score: KillSwitchScore;
  decision: 'BUILD' | 'OPTIONAL_TEST' | 'KILL';
  justification: string;
}

export interface KillSwitchDecisionRule {
  buildThreshold: 85;
  optionalTestMin: 75;
  optionalTestMax: 84;
  killThreshold: 74;
}

// Reference Game Architecture Types
export interface GameArchitecture {
  frontend: FrontendLayer;
  backend: BackendLayer;
  aiContentEngine: AIContentEngine;
  automationLayer: AutomationLayer;
  payments: PaymentsLayer;
  deployment: DeploymentLayer;
}

export interface FrontendLayer {
  purpose: 'display_and_interaction';
  tech: ('HTML' | 'CSS' | 'JS' | 'React')[];
  features: {
    login: 'email' | 'magic_link';
    gameScreen: boolean;
    progressIndicator: boolean;
    paywallGate: boolean;
  };
  mobileFirst: boolean;
  complexState: boolean;
}

export interface BackendLayer {
  purpose: 'control_everything';
  modules: {
    userState: boolean; // progress, streaks
    gameRulesEngine: boolean;
    scoringProgression: boolean;
    subscriptionValidation: boolean;
  };
}

export interface AIContentEngine {
  purpose: 'infinite_content_zero_effort';
  pattern: {
    promptTemplate: boolean;
    constraints: boolean;
    generateDaily: boolean;
    generateOnDemand: boolean;
    cacheResults: boolean;
  };
  contentTypes: ('trivia' | 'puzzles' | 'challenges' | 'scenarios')[];
}

export interface AutomationLayer {
  scheduledJobs: {
    dailyContentRefresh: boolean;
    difficultyScaling: boolean;
    contentExpiry: boolean;
    emailReminders: boolean;
  };
  noDashboardsInitially: boolean;
}

export interface PaymentsLayer {
  provider: 'Stripe' | 'Paddle';
  model: 'monthly_subscription';
  optionalPacks: boolean;
  maxTrialDays: 7;
}

export interface DeploymentLayer {
  frontend: 'GitHub_Pages' | 'Vercel';
  backend: 'serverless';
  automation: 'cron_based';
  opsLevel: 'zero';
}

// Full Game Concept Analysis
export interface GameConceptAnalysis {
  concept: GameConceptOutput;
  monetization: MonetizationOutput;
  automation: AutomationOutput;
  killSwitch: KillSwitchOutput;
  architecture: GameArchitecture;
  timestamp: Date;
}
