/**
 * Agent 1: 🎯 Game Concept Sniper
 * 
 * Role: Game Concept Sniper
 * 
 * Goal: Identify simple, AI-driven game concepts that can monetize with
 * small audiences and require near-zero manual content creation.
 * 
 * Backstory: Expert in casual, serious, and niche games. Allergic to
 * multiplayer, live ops, and content debt. Focused on games that behave like SaaS.
 */

import {
  CrewAIAgent,
  GameConceptOutput,
  GameConceptValidation,
} from '../../types/agents';

export class GameConceptSniper implements CrewAIAgent {
  public readonly role = 'Game Concept Sniper';
  
  public readonly goal = 
    'Identify simple, AI-driven game concepts that can monetize with small audiences ' +
    'and require near-zero manual content creation.';
  
  public readonly backstory = 
    'Expert in casual, serious, and niche games. Allergic to multiplayer, ' +
    'live ops, and content debt. Focused on games that behave like SaaS.';

  public readonly strictInstructions = [
    'Game must be single-player',
    'Content must be auto-generated',
    'Must be web-first (desktop/mobile browser)',
    'Core loop must be ≤ 3 actions',
    'No storylines requiring manual design',
    'No levels requiring manual design',
  ];

  public readonly autoRejectConditions = [
    'Multiplayer',
    'Needs weekly content updates',
    'Depends on ads or virality',
  ];

  /**
   * Validate a game concept against strict requirements
   */
  public validateConcept(concept: Partial<GameConceptValidation>): {
    isValid: boolean;
    rejectionReasons: string[];
  } {
    const rejectionReasons: string[] = [];

    // Check strict requirements
    if (concept.isSinglePlayer === false) {
      rejectionReasons.push('Game must be single-player');
    }
    
    if (concept.isContentAutoGenerated === false) {
      rejectionReasons.push('Content must be auto-generated');
    }
    
    if (concept.isWebFirst === false) {
      rejectionReasons.push('Game must be web-first (desktop/mobile browser)');
    }
    
    if (concept.coreLoopSteps !== undefined && concept.coreLoopSteps > 3) {
      rejectionReasons.push('Core loop must be ≤ 3 actions');
    }
    
    if (concept.requiresManualDesign === true) {
      rejectionReasons.push('No storylines or levels requiring manual design');
    }

    // Check auto-reject conditions
    if (concept.isMultiplayer === true) {
      rejectionReasons.push('AUTO-REJECT: Multiplayer not allowed');
    }
    
    if (concept.needsWeeklyUpdates === true) {
      rejectionReasons.push('AUTO-REJECT: Cannot require weekly content updates');
    }
    
    if (concept.dependsOnAdsOrVirality === true) {
      rejectionReasons.push('AUTO-REJECT: Cannot depend on ads or virality');
    }

    return {
      isValid: rejectionReasons.length === 0,
      rejectionReasons,
    };
  }

  /**
   * Generate a game concept analysis
   */
  public analyzeGameConcept(
    gameConcept: string,
    targetAudience: string,
    coreGameLoop: string[],
    whatAIGenerates: string,
    whyUsersPay: string
  ): GameConceptOutput {
    // Validate core loop length
    if (coreGameLoop.length > 3) {
      throw new Error('Core game loop must have ≤ 3 steps');
    }

    return {
      gameConcept,
      targetAudience,
      coreGameLoop,
      whatAIGenerates,
      whyUsersPay,
    };
  }

  /**
   * Format output according to expected format
   */
  public formatOutput(output: GameConceptOutput): string {
    return `GAME CONCEPT:
${output.gameConcept}

TARGET AUDIENCE:
${output.targetAudience}

CORE GAME LOOP (max 3 steps):
${output.coreGameLoop.map((step, index) => `${index + 1}. ${step}`).join('\n')}

WHAT AI GENERATES:
${output.whatAIGenerates}

WHY USERS PAY (not play):
${output.whyUsersPay}`;
  }

  /**
   * Generate sample game concepts that meet all criteria
   */
  public getSampleConcepts(): GameConceptOutput[] {
    return [
      {
        gameConcept: 'Daily Logic Puzzler - AI generates unique logic puzzles daily that increase in difficulty based on user performance',
        targetAudience: 'Adults 25-55 seeking mental stimulation during commutes or breaks, willing to pay for ad-free premium brain training',
        coreGameLoop: [
          'Read AI-generated logic puzzle',
          'Input solution',
          'Receive score and streak update',
        ],
        whatAIGenerates: 'Unique logic puzzles, difficulty curves, hint systems, solution explanations',
        whyUsersPay: 'Unlimited daily puzzles, tracked progress, personalized difficulty, no ads - positions as affordable brain training subscription',
      },
      {
        gameConcept: 'Word Mastery Challenge - AI creates vocabulary challenges from curated word banks with spaced repetition',
        targetAudience: 'Language learners, students preparing for exams (SAT, GRE, IELTS), professionals improving communication',
        coreGameLoop: [
          'View AI-generated word challenge',
          'Select correct answer',
          'Review and progress',
        ],
        whatAIGenerates: 'Context sentences, difficulty progression, personalized review schedules, performance analytics',
        whyUsersPay: 'Measurable vocabulary growth, exam preparation value, progress tracking, certificate of mastery',
      },
      {
        gameConcept: 'Number Sense Trainer - AI generates arithmetic and number pattern challenges with adaptive difficulty',
        targetAudience: 'Parents wanting math practice for kids, adults maintaining mental sharpness, professionals in quantitative fields',
        coreGameLoop: [
          'Solve AI-generated number challenge',
          'Submit answer',
          'Track improvement metrics',
        ],
        whatAIGenerates: 'Number puzzles, arithmetic challenges, pattern recognition problems, progress reports',
        whyUsersPay: 'Proven improvement metrics, personalized training plans, family accounts, progress certificates',
      },
    ];
  }

  /**
   * Get the system prompt for AI integration
   */
  public getSystemPrompt(): string {
    return `You are the ${this.role}.

${this.goal}

BACKSTORY:
${this.backstory}

STRICT INSTRUCTIONS (non-negotiable):
Game must be:
${this.strictInstructions.map(i => `- ${i}`).join('\n')}

Auto-reject if:
${this.autoRejectConditions.map(c => `- ${c}`).join('\n')}

Expected Output (exact format):
GAME CONCEPT:
TARGET AUDIENCE:
CORE GAME LOOP (max 3 steps):
WHAT AI GENERATES:
WHY USERS PAY (not play):

Remember: Games are products, not art projects. Focus on monetization with small audiences.`;
  }
}

export const gameConceptSniper = new GameConceptSniper();
