import { gameConceptSniper } from '../../services/agents/GameConceptSniper';

describe('GameConceptSniper', () => {
  describe('agent properties', () => {
    it('should have correct role', () => {
      expect(gameConceptSniper.role).toBe('Game Concept Sniper');
    });

    it('should have defined goal', () => {
      expect(gameConceptSniper.goal).toContain('AI-driven game concepts');
      expect(gameConceptSniper.goal).toContain('small audiences');
    });

    it('should have strict instructions', () => {
      expect(gameConceptSniper.strictInstructions).toHaveLength(6);
      expect(gameConceptSniper.strictInstructions).toContain('Game must be single-player');
    });

    it('should have auto-reject conditions', () => {
      expect(gameConceptSniper.autoRejectConditions).toHaveLength(3);
      expect(gameConceptSniper.autoRejectConditions).toContain('Multiplayer');
    });
  });

  describe('validateConcept', () => {
    it('should validate a valid concept', () => {
      const result = gameConceptSniper.validateConcept({
        isSinglePlayer: true,
        isContentAutoGenerated: true,
        isWebFirst: true,
        coreLoopSteps: 3,
        requiresManualDesign: false,
        isMultiplayer: false,
        needsWeeklyUpdates: false,
        dependsOnAdsOrVirality: false,
      });

      expect(result.isValid).toBe(true);
      expect(result.rejectionReasons).toHaveLength(0);
    });

    it('should reject non-single-player games', () => {
      const result = gameConceptSniper.validateConcept({
        isSinglePlayer: false,
      });

      expect(result.isValid).toBe(false);
      expect(result.rejectionReasons).toContain('Game must be single-player');
    });

    it('should reject games without auto-generated content', () => {
      const result = gameConceptSniper.validateConcept({
        isContentAutoGenerated: false,
      });

      expect(result.isValid).toBe(false);
      expect(result.rejectionReasons).toContain('Content must be auto-generated');
    });

    it('should reject non-web-first games', () => {
      const result = gameConceptSniper.validateConcept({
        isWebFirst: false,
      });

      expect(result.isValid).toBe(false);
      expect(result.rejectionReasons).toContain('Game must be web-first (desktop/mobile browser)');
    });

    it('should reject games with more than 3 core loop steps', () => {
      const result = gameConceptSniper.validateConcept({
        coreLoopSteps: 5,
      });

      expect(result.isValid).toBe(false);
      expect(result.rejectionReasons).toContain('Core loop must be ≤ 3 actions');
    });

    it('should reject games requiring manual design', () => {
      const result = gameConceptSniper.validateConcept({
        requiresManualDesign: true,
      });

      expect(result.isValid).toBe(false);
      expect(result.rejectionReasons).toContain('No storylines or levels requiring manual design');
    });

    it('should auto-reject multiplayer games', () => {
      const result = gameConceptSniper.validateConcept({
        isMultiplayer: true,
      });

      expect(result.isValid).toBe(false);
      expect(result.rejectionReasons).toContain('AUTO-REJECT: Multiplayer not allowed');
    });

    it('should auto-reject games needing weekly updates', () => {
      const result = gameConceptSniper.validateConcept({
        needsWeeklyUpdates: true,
      });

      expect(result.isValid).toBe(false);
      expect(result.rejectionReasons).toContain('AUTO-REJECT: Cannot require weekly content updates');
    });

    it('should auto-reject games depending on ads or virality', () => {
      const result = gameConceptSniper.validateConcept({
        dependsOnAdsOrVirality: true,
      });

      expect(result.isValid).toBe(false);
      expect(result.rejectionReasons).toContain('AUTO-REJECT: Cannot depend on ads or virality');
    });

    it('should collect multiple rejection reasons', () => {
      const result = gameConceptSniper.validateConcept({
        isSinglePlayer: false,
        isMultiplayer: true,
        needsWeeklyUpdates: true,
      });

      expect(result.isValid).toBe(false);
      expect(result.rejectionReasons.length).toBeGreaterThan(1);
    });
  });

  describe('analyzeGameConcept', () => {
    it('should create valid game concept output', () => {
      const output = gameConceptSniper.analyzeGameConcept(
        'Daily Logic Puzzler',
        'Adults 25-55',
        ['Read puzzle', 'Solve', 'Score'],
        'Logic puzzles',
        'Premium features'
      );

      expect(output.gameConcept).toBe('Daily Logic Puzzler');
      expect(output.targetAudience).toBe('Adults 25-55');
      expect(output.coreGameLoop).toHaveLength(3);
      expect(output.whatAIGenerates).toBe('Logic puzzles');
      expect(output.whyUsersPay).toBe('Premium features');
    });

    it('should throw error for more than 3 core loop steps', () => {
      expect(() => {
        gameConceptSniper.analyzeGameConcept(
          'Game',
          'Audience',
          ['Step 1', 'Step 2', 'Step 3', 'Step 4'],
          'AI content',
          'Value'
        );
      }).toThrow('Core game loop must have ≤ 3 steps');
    });

    it('should accept exactly 3 core loop steps', () => {
      const output = gameConceptSniper.analyzeGameConcept(
        'Game',
        'Audience',
        ['Step 1', 'Step 2', 'Step 3'],
        'AI content',
        'Value'
      );

      expect(output.coreGameLoop).toHaveLength(3);
    });
  });

  describe('formatOutput', () => {
    it('should format output correctly', () => {
      const output = gameConceptSniper.analyzeGameConcept(
        'Test Game',
        'Test Audience',
        ['Action 1', 'Action 2'],
        'AI generates tests',
        'Users pay for value'
      );

      const formatted = gameConceptSniper.formatOutput(output);

      expect(formatted).toContain('GAME CONCEPT:');
      expect(formatted).toContain('Test Game');
      expect(formatted).toContain('TARGET AUDIENCE:');
      expect(formatted).toContain('Test Audience');
      expect(formatted).toContain('CORE GAME LOOP');
      expect(formatted).toContain('1. Action 1');
      expect(formatted).toContain('2. Action 2');
      expect(formatted).toContain('WHAT AI GENERATES:');
      expect(formatted).toContain('WHY USERS PAY');
    });
  });

  describe('getSampleConcepts', () => {
    it('should return sample concepts', () => {
      const samples = gameConceptSniper.getSampleConcepts();

      expect(samples.length).toBeGreaterThan(0);
      samples.forEach(sample => {
        expect(sample.gameConcept).toBeDefined();
        expect(sample.targetAudience).toBeDefined();
        expect(sample.coreGameLoop).toBeDefined();
        expect(sample.coreGameLoop.length).toBeLessThanOrEqual(3);
        expect(sample.whatAIGenerates).toBeDefined();
        expect(sample.whyUsersPay).toBeDefined();
      });
    });
  });

  describe('getSystemPrompt', () => {
    it('should return a valid system prompt', () => {
      const prompt = gameConceptSniper.getSystemPrompt();

      expect(prompt).toContain('Game Concept Sniper');
      expect(prompt).toContain('STRICT INSTRUCTIONS');
      expect(prompt).toContain('Auto-reject');
      expect(prompt).toContain('Expected Output');
    });
  });
});
